# Generated by Django 4.2.5 on 2023-09-26 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('site', models.CharField(max_length=50)),
                ('instagram', models.CharField(max_length=50)),
                ('facebook', models.CharField(max_length=50)),
                ('twitter', models.CharField(max_length=50)),
                ('nacionalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nacionalidade')),
            ],
        ),
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('site', models.CharField(max_length=50)),
                ('instagram', models.CharField(max_length=50)),
                ('facebook', models.CharField(max_length=50)),
                ('twitter', models.CharField(max_length=50)),
                ('nacionalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nacionalidade')),
            ],
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='nacionalidade',
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.AlterField(
            model_name='filme',
            name='diretor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.diretor'),
        ),
        migrations.AlterField(
            model_name='filmeator',
            name='ator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ator'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='diretor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.diretor'),
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
